components:
    parameters:
      offset:
        in: query
        name: offset
        description: The number of items to skip before starting to collect the result set
        schema:
          type: integer
          minimum: 0
          default: '0'
      limit:
        in: query
        name: limit
        description: The numbers of items to return
        schema:
          type: integer
          minimum: 0
          default: 10
      todolistId:
        in: path
        name: todolistId
        description: Todolist ID
        required: true
        schema:
          type: string
          format: uuid
    